plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.+'      // 使用 6.0.x 最新版
}
pluginManagement {
    repositories {
        gradlePluginPortal()    // Gradle 官方插件门户
        mavenCentral()          // Maven Central
        maven {                // Forge 的 Maven 仓库（必加）
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

jar {
    manifest {
        attributes 'Specification-Title': 'wheeljump',
                   'Specification-Version': '1.0',
                   'Implementation-Title': 'WheelJump',
                   'Implementation-Version': '1.0.0'
    }
}
